PSI Projekat/BrzeBoljeJeftinije.Messenger.UI/Controllers/AdminController.cs
/**
 * AuthController.cs
 * Autor: Nikola Pavlović
 */
using BrzeBoljeJeftinije.Messenger.DB;
using BrzeBoljeJeftinije.Messenger.UI.Helpers;
using BrzeBoljeJeftinije.Messenger.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrzeBoljeJeftinije.Messenger.UI.Controllers
{
    /**
     * <summary>Klasa za prijavu/odjavu administratora i akcije koje obavlja administrator</summary>
     * 
     *  <remarks>
     *  Verzija: 1.0
     *  </remarks>
     */
    public class AdminController : BaseController
    {

        public AdminController(IDBProvider dbProvider)
            : base(dbProvider)
        {
        }

        /**
         * <summary>Prikazuje stranicu sa koje administratori vrše upravljanje korisnicima</summary>
         */
        [AdminAuthorize]
        public ActionResult Index()
        {
            return View();
        }

        /**
         * <summary>Prikazuje stranicu za prijavu administratora</summary>
         */
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        /**
         * <summary>Prijavljuje administratora na sistem</summary>
         * <param name="model">Podaci iz HTTP zahteva</param>
         */
        [HttpPost]
        public ActionResult Login(AdminUser model)
        {
            var user = dbProvider.GetAdminUser(model.Username);
            if (user == null || !user.ValidatePassword(model.Password))
            {
                ViewData["AdminError"] = "Neispravno ime ili lozinka";
                return View();
            }
            SessionData.AdminUser = user;
            return Redirect(Url.Action("Index"));
        }

        /**
         * <summary>Odjavljuje administratora sa sistema</summary>
         */
        [HttpGet]
        [AdminAuthorize]
        public ActionResult Logout()
        {
            SessionData.AdminUser = null;
            return Redirect(Url.Action("Login"));
        }

        /**
         * <summary>Pretražuje korisnike sa zadatim imenom</summary>
         */
        [HttpPost]
        [AdminAuthorize]
        public ActionResult Search(string name)
        {
            if (name == null) return HttpNotFound();
            var users = dbProvider.SearchUsersByName(name);
            var result = users.Select(x => new
            {
                id = x.Id,
                name = x.Name,
                picture = Url.Action("Picture", "User", new {id=x.Id, rand=DateTime.Now.ToString()}),
                banDate= x.BannedUntil==null?DateTime.Now:x.BannedUntil,
                status= (x.BannedUntil==null || x.BannedUntil<=DateTime.Now.Date)?"ok":"ban",
            }).ToList();
            return Json(result);
        }

        /**
         * <summary>Menja status (banuje, odbanuje, menja datum bana) zadatom korisniku</summary>
         * <param name="model">Podaci iz HTTP zahteva</param>
         */
        [HttpPost]
        [AdminAuthorize]
        public ActionResult UpdateStatus(UpdateStatusModel model)
        {
            if (!ModelState.IsValid) return HttpNotFound();
            var user = dbProvider.GetUserByID(model.Id, false);
            if (user == null) return HttpNotFound();
            if(model.Status=="ok")
            {
                user.BannedUntil = null;
                dbProvider.UpdateUser(user);
                return Content("OK");
            }
            else
            {
                if(model.ExpiryDate<=DateTime.Now)
                {
                    return Content("FAIL:Datum bana je neispravan");
                }
                user.BannedUntil = model.ExpiryDate.Date;
                dbProvider.UpdateUser(user);
                return Content("OK");
            }
        }

        /**
         * <summary>Setuje novu lozinku ulogovanom korisniku</summary>
         * <param name="model">Podaci iz HTTP zahteva</param>
         */
        [HttpPost]
        [AdminAuthorize]
        public ActionResult MyPassword(string password)
        {
            if (password == null) return HttpNotFound();
            if (password.Length == 0) return HttpNotFound();
            var user = SessionData.AdminUser;
            user.SetPassword(password);
            SessionData.AdminUser = user;
            dbProvider.UpdateAdminUser(user);
            return Content("OK");
        }

        /**
         * <summary>Registruje novog administratora</summary>
         * <param name="model">Podaci iz HTTP zahteva</param>
         */
        [HttpPost]
        [AdminAuthorize]
        public ActionResult Register(AdminUser user)
        {
            if(string.IsNullOrWhiteSpace(user.Username) || string.IsNullOrWhiteSpace(user.Password))
            {
                return HttpNotFound();
            }
            var oldUser = dbProvider.GetAdminUser(user.Username);
            if(oldUser!=null)
            {
                return Content("FAIL:Već postoji administrator pod tim imenom");
            }
            var newAdmin = new DB.Entities.AdminUser
            {
                Username=user.Username
            };
            newAdmin.SetPassword(user.Password);
            dbProvider.StoreAdminUser(newAdmin);
            return Content("OK");
            
        }
    }
}
 

PSI Projekat/BrzeBoljeJeftinije.Messenger.UI/Controllers/AuthController.cs
/**
 *  AuthController.cs
 *  Autor: Nikola Pavlović
 */
using BrzeBoljeJeftinije.Messenger.DB;
using BrzeBoljeJeftinije.Messenger.DB.Entities;
using BrzeBoljeJeftinije.Messenger.UI.Helpers;
using BrzeBoljeJeftinije.Messenger.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Security;
using System.Text;
namespace BrzeBoljeJeftinije.Messenger.UI.Controllers
{
    /**
     *  <summary>Klasa za prijavu, odjavu i kreiranje naloga korisnika</summary>
     *  
     *  <remarks>
     *  Verzija: 1.0
     *  </remarks>
     */
    public class AuthController : BaseController
    {
        public AuthController(IDBProvider dbProvider)
            : base(dbProvider)
        {
        }

        /**
         * <summary>izvršava prijavu i eventualno kreiranje korisničkog naloga</summary>
         * <param name="model">Podaci iz HTTP zahteva</param>
         */
        [HttpPost]
        public ActionResult Index(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                if(model.Signature=="sim")
                {
                    if (!Config.SimLoginEnabled) return HttpNotFound();
                    var name = model.Certificate.Split(':')[1];
                    var id= model.Certificate.Split(':')[0];
                    var secret = model.Certificate.Split(':')[2];
                    var user = GetOrCreateUser(name, id, secret);
                    if (user == null) return HttpNotFound();
                    if(user.BannedUntil!=null && user.BannedUntil>DateTime.Now.Date)
                    {
                        return Content("FAIL:Vaš korisnički nalog je blokiran do " + ((DateTime)user.BannedUntil).ToString("dd.MM.yyyy."));
                    }
                    SessionData.User = user;
                    return Content("OK");
                }
                else
                {
                    var certificate = CryptoHelper.LoadCert(model.Certificate);
                    if (!CryptoHelper.ValidateCert(certificate) || !CryptoHelper.VerifySignature(certificate, SessionData.SignatureAuthToken, model.Signature))
                    {
                        return HttpNotFound();
                    }
                    else
                    {
                        SessionData.SignatureAuthToken = null;
                        var user = GetOrCreateUser(certificate);
                        if (user.BannedUntil != null && user.BannedUntil > DateTime.Now.Date)
                        {
                            return Content("FAIL:Vaš korisnički nalog je blokiran do " + ((DateTime)user.BannedUntil).ToString("dd.MM.yyyy."));
                        }
                        SessionData.User = user;
                        return Content("OK");
                    }
                }
            }
            else
            {
                return Content("FAIL:Došlo je do nepoznate greške");
            }
        }

        /**
         * <summary>Izvršava odjavu korisnika</summary>
         */
        [HttpGet]
        [CardAuthorize]
        public ActionResult Logout()
        {
            SessionData.User = null;
            return RedirectToAction("Index", "Home");
        }

        /**
         * <summary>Vraća objekat simulacionog korisnika iz baze, po potrebi ga kreira</summary>
         * <param name="simName">Automatski generisano ime</param>
         * <param name="simId">ID koji se koristi umesto serijskog broja sertifikata</param>
         * <param name="secret">Tajni, automatski generisani podatak, koristi se da bi se
         * koliko toliko sprečila krađa simulacionih naloga</param>
         * <returns>Objekat koji predstavlja korisnika, null ako operacija ne uspe</returns>
         */
        private User GetOrCreateUser(string simName, string simId, string secret)
        {
            if (!simId.StartsWith("SIM")) return null;
            var user = dbProvider.GetUserByCertHash(simId, false);
            if (user != null)
            {
                if (!Encoding.UTF8.GetString(user.Certificate).StartsWith(secret)) return null;
                user.RtID = SessionData.SessionId;
                dbProvider.UpdateUser(user);
                return user;
            }
            user = new User
            {
                CertHash = simId,
                Certificate = Encoding.UTF8.GetBytes(secret),
                Name = simName,
                RtID = SessionData.SessionId
            };
            user.PictureType = "image/png";
            user.Picture = System.IO.File.ReadAllBytes(HostingEnvironment.MapPath(@"~/Content/img/user.png"));
            dbProvider.StoreUser(user);
            return user;
        }

        /**
         * <summary>Dohvata (po potrebi kreira) objekat korisnika koji odgovara učitanom sertifikatu sa
         * lične karte</summary>
         * <param name="cert">Sertifikat očitan sa lične karte</param>
         * <returns>Objekat koji predstavlja korisnika, null ako operacija ne uspe</returns>
         */
        private User GetOrCreateUser(X509Certificate2 cert)
        {
            var user = dbProvider.GetUserByCertHash(cert.GetSerialNumberString(), false);
            if (user != null)
            {
                user.RtID= SessionData.SessionId;
                dbProvider.UpdateUser(user);
                return user;
            }
            user = CryptoHelper.GetUserFromCert(cert);
            user.PictureType = "image/png";
            user.Picture = System.IO.File.ReadAllBytes(HostingEnvironment.MapPath(@"~/Content/img/user.png"));
            user.RtID = SessionData.SessionId;
            dbProvider.StoreUser(user);
            return user;
        }

        /**
         * <summary>Vraća token koji treba potpisati prilikom prijave ličnom kartom</summary>
         */
        [HttpPost]
        public ActionResult GetSignatureToken()
        {
            if (SessionData.SignatureAuthToken == null)
            {
                SessionData.SignatureAuthToken = CryptoHelper.GetRandomToken();
            }
            return Content(SessionData.SignatureAuthToken);
        }
    }
}

PSI Projekat/BrzeBoljeJeftinije.Messenger.UI/Controllers/SettingsController.cs
/**
 * SettingsController.cs
 * Autor: Nikola Pavlović
 */
using BrzeBoljeJeftinije.Messenger.UI.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrzeBoljeJeftinije.Messenger.UI.Controllers
{
    /**
     * <summary>Prikazuje stranicu za podešavanja</summary>
     * 
     *  <remarks>
     *  Verzija: 1.0
     *  </remarks>
     */
    [CardAuthorize]
    public class SettingsController : Controller
    {
        /**
         * <summary>Prikazuje stranicu za podešavanja</summary>
         */
        public ActionResult Index()
        {
            return View();
        }
    }
}

PSI Projekat/BrzeBoljeJeftinije.Messenger.UI/Views/Shared/_Layout.cshtml
@using BrzeBoljeJeftinije.Messenger.UI.Helpers;
@{
    var currentController = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();
    var currentAction = HttpContext.Current.Request.RequestContext.RouteData.Values["action"].ToString();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
    <title>
        Hello Messenger
    </title>
    @Styles.Render("~/Content/bundled_css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/signalR")
    @Scripts.Render("~/bundles/cardreader")
    @Scripts.Render("~/bundles/js")
    <script src="signalr/hubs"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>
<body>
    <script>
        var sessionId = "@HttpContext.Current.Session.SessionID";
    </script>
    <div class="modal" id="message-box-modal">
        <div class="modal-inner modal-inner-smaller modal-inner-noscroll">
            <a href="#"><div style="float:right;padding-right:16px;font-family:'Segoe UI'" onclick="closeModal()"><i class="fa fa-close pull-right" aria-hidden="true"></i></div></a><br />
            <h2 class="info-part">OBAVEŠTENJE</h2>
            <h2 class="alert-part">UPOZORENJE</h2>
            <div style="text-align:center;" class="alert-part"><i class="fa fa-warning fa-4x" style="color:red" aria-hidden="true"></i></div>
            <div style="text-align:center;" class="info-part"><i class="fa fa-info-circle fa-4x" style="color:blue" aria-hidden="true"></i></div>
            <div class="message-box-text" style="text-align:center"></div>
            <input type="button" class="form-control" value="Nastavi" onclick="closeModal()" />
        </div>
    </div>
    <div class="modal" id="prompt-modal">
        <div class="modal-inner modal-inner-smaller modal-inner-noscroll">
            <div style="text-align:center;"><i class="fa fa-question-circle fa-4x" aria-hidden="true"></i></div>
            <div class="message-box-text" style="text-align:center"></div>
            <input type="button" class="form-control" style="width:50%;float:left" value="Odustani" onclick="promptReject()" />
            <input type="button" class="form-control" style="width:50%;float:right" value="Nastavi" onclick="promptAccept()" />
        </div>
    </div>
    <div class="modal" id="generic-modal">
        <div class="modal-inner">
            <a href="#"><div style="float:right;padding-right:16px;font-family:'Segoe UI'" onclick="closeModal()"><i class="fa fa-close pull-right" aria-hidden="true"></i></div></a><br />
            <div class="generic-content"></div>
        </div>
    </div>
    <nav id="nav-menu-open">
        <div class="w3-top" ; style="text-align:center;overflow-x:hidden">
            <a href="#" onclick="openNavMenu()"><i id="open-nav-button" class="fa fa-arrow-circle-down" aria-hidden="true"></i></a>
        </div>
    </nav>
    <nav id="nav-menu">
        <div class="w3-top">
            <div class="w3-bar w3-xlarge w3-black w3-opacity w3-hover-opacity-off" id="myNavbar">
                @if (currentController == "Messages")
                {
                    <a href="@Url.Action("Index","Messages")" class="w3-bar-item w3-button">PORUKE</a>
                    <a href="#" onclick="showModal('#friendsearch')" class="w3-bar-item w3-button">DODAJ PRIJATELJE</a>
                    <a href="@Url.Action("Index","Settings")" class="w3-bar-item w3-button">PODEŠAVANJA</a>
                }
                else if (currentController == "Settings")
                {
                    <a href="@Url.Action("Index","Messages")" class="w3-bar-item w3-button">PORUKE</a>
                }
                else if (currentController == "Home")
                {
                    <a href="@Url.Action("Index", "Home")" class="w3-bar-item w3-button">POČETAK</a>
                    <a href="#manual" class="w3-bar-item w3-button">UPUTSTVO</a>
                    <a href="#team" class="w3-bar-item w3-button">TIM</a>
                    <a href="#googleMap" class="w3-bar-item w3-button">KONTAKT</a>
                    <a href="@Url.Action("Login", "Admin")" class="w3-bar-item w3-button">ADMINISTRACIJA</a>
                }
                else
                {
                    <a href="@Url.Action("Index", "Home")" class="w3-bar-item w3-button">POČETAK</a>
                    if (currentAction == "Index")
                    {
                        <a href="javascript:registerNewAdmin()" class="w3-bar-item w3-button">REGISTRUJ NOVOG ADMINISTRATORA</a>
                        <a href="javascript:showModal('#set-my-password')" class="w3-bar-item w3-button">PROMENI LOZINKU</a>
                        <a href="@Url.Action("Logout","Admin")" class="w3-bar-item w3-button">ODJAVI SE</a>
                    }
                }
                @if (SessionData.User != null)
                {
                    <a href="@Url.Action("Logout","Auth")" class="w3-bar-item w3-button">ODJAVI SE</a>
                    <div class="profile-info">
                        <img id="menu-profile-pic" src="@Url.Action("MyPicture", "User", new { rand=DateTime.Now.ToString() })" alt="Person" width="96" height="96">
                        @SessionData.User.Name
                    </div>
                }
            </div>
        </div>
    </nav>
    @if (currentController != "Home")
    {
        <div class="root-div">
            @RenderBody()
        </div>
    }
    else
    {
        @RenderBody()
    }


    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @if (TempData["ErrorMessage"] != null)
    {
        <script>
            $(document).ready(() => {
                showAlertBox("@TempData["ErrorMessage"]");
            });
        </script>
    }
</body>
</html>