PSI Projekat/BrzeBoljeJeftinije.Messenger.UI/Controllers/GroupController.cs
/**
 * GroupController.cs
 * Autor: Nikola Pavlović
 */
using BrzeBoljeJeftinije.Messenger.DB;
using BrzeBoljeJeftinije.Messenger.DB.Entities;
using BrzeBoljeJeftinije.Messenger.UI.Helpers;
using BrzeBoljeJeftinije.Messenger.UI.Models;
using BrzeBoljeJeftinije.Messenger.UI.SignalR;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BrzeBoljeJeftinije.Messenger.UI.Controllers
{
    /**
     * <summary>Sadrži akcije za upravljanje i pregled korisničkih grupa</summary>
     * 
     *  <remarks>
     *  Verzija: 1.0
     *  </remarks>
     */
    [CardAuthorize]
    public class GroupController : BaseController
    {
        public GroupController(IDBProvider dbProvider) : base(dbProvider)
        {
        }

        /**
         * <summary>Vraća listu grupa kojima pripada trenutni korisnik</summary>
         */
        [HttpPost]
        public ActionResult My()
        {
            var groups = dbProvider.GetGroupsForUser(SessionData.User);
            var requests = dbProvider.GetUnresolvedFriendRequests(SessionData.User).Union(dbProvider.GetSentFriendRequests(SessionData.User)).ToList();
            var friends = dbProvider.GetFriends(SessionData.User);
            groups.Sort((g1, g2) =>
            {
                var t1 = g1.LastMessage != null ? (DateTime)g1.LastMessage : g1.Timestamp;
                var t2 = g2.LastMessage != null ? (DateTime)g2.LastMessage : g2.Timestamp;
                return (int)((t1 - t2).TotalSeconds);
            });
            requests.Sort((r1, r2) =>
            {
                return (int)((r1.Timestamp - r2.Timestamp).TotalSeconds);
            });
            List<object> result = new List<object>();
            foreach (var group in groups)
            {
                var members = dbProvider.GetUsersInGroup(group);
                string pictureUrl = "";
                string groupName = group.Name;
                int? otherId = null;
                if (group.Binary)
                {
                    otherId = members.First(x => x.Id != SessionData.User.Id).Id;
                    pictureUrl = Url.Action("Picture", "User", new { id = otherId, rand = DateTime.Now.ToString() });
                    groupName = members.First(x => x.Id != SessionData.User.Id).Name;
                }
                else
                {
                    pictureUrl = "/Group/Picture/"+group.Id;
                }
                result.Add(new
                {
                    id = group.Id,
                    timestamp = group.LastMessage != null ? group.LastMessage : group.Timestamp,
                    type = "group",
                    unread = group.ContainsUnread,
                    admin = group.IsAdmin,
                    binary = group.Binary,
                    members,
                    picture = pictureUrl,
                    otherId,
                    name = groupName
                });
            }
            foreach (var request in requests)
            {
                result.Add(new
                {
                    id = "r" + request.SenderId,
                    timestamp = request.Timestamp,
                    type = "request",
                    sent = request.SenderId == SessionData.User.Id,
                    admin = false,
                    picture = Url.Action("Picture", "User", new { id = (request.SenderId == SessionData.User.Id ? request.ReceiverId : request.SenderId), rand = DateTime.Now.ToString() }),
                    otherId = request.SenderId == SessionData.User.Id ? request.ReceiverId : request.SenderId,
                    name = dbProvider.GetUserByID(request.SenderId == SessionData.User.Id ? request.ReceiverId : request.SenderId, false).Name,
                });
            }
            return Json(result);
        }

        /**
         * <summary>Prikazuje formu za editovanje postojeće grupe ili prikazuje praznu formu za kreiranje nove grupe
         * </summary>
         * <param name="id">Id grupe koja se edituje, ako je <c>null</c> prikazuje se prazna forma za kreiranje
         * nove grupe</param>
         * 
         */
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if(id!=null)
            {
                var group = dbProvider.GetGroupsForUser(SessionData.User).FirstOrDefault(x => x.Id == (int)id && (bool)x.IsAdmin);
                if (group == null) return HttpNotFound();
                var model = new GroupModel
                {
                    Id = group.Id,
                    Name = group.Name
                };
                model.SetMembers(dbProvider.GetUsersInGroup(group));
                return PartialView("~/Views/Group/Edit.cshtml", model);
            }
            else
            {
                return PartialView("~/Views/Group/Edit.cshtml", new GroupModel
                {
                    Members = "[]",
                    Name = "",
                });
            }
        }

        /**
         * <summary>Edituje postojeću ili kreira novu grupu</summary>
         * <param name="model">Podaci iz HTTP zahteva</param>
         */
        [HttpPost]
        public ActionResult Edit(GroupModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == null)
                {
                    if (model.Picture == null)
                    {
                        return Content("FAIL:Niste poslali sliku");
                    }
                    var image = ImageManipulation.LoadImage(model.Picture.InputStream);
                    if (image == null)
                    {
                        return Content("FAIL:Niste poslali sliku");
                    }
                    image = ImageManipulation.ResizeImage(image, 160, 160);
                    var group = dbProvider.CreateGroup(new DB.Entities.Group
                    {
                        Binary = false,
                        Name = model.Name,
                        Timestamp = DateTime.Now,
                        Picture = ImageManipulation.StoreImage(image),
                        PictureType = ImageManipulation.OutputImageFormat,
                    });
                    var users = model.GetMembers();
                    var friends = dbProvider.GetFriends(SessionData.User).Union(dbProvider.GetUsersInGroup(group));
                    foreach (var user in users)
                    {
                        if (user.Id == SessionData.User.Id || friends.All(x => x.Id != user.Id))
                        {
                            return HttpNotFound();
                        }
                    }
                    dbProvider.AddUsersToGroup(users, group, false);
                    dbProvider.AddUsersToGroup(new List<DB.Entities.User> { SessionData.User }, group, true);
                    dbProvider.CommitIfNecessary();
                    foreach (var user in users)
                    {
                        MessengerHub.CallRefresh(friends.First(x => x.Id == user.Id).RtID);
                    }                    
                    return Content("OK");
                }
                else
                {
                    Image picture = null;
                    if(model.Picture!=null)
                    {
                        picture = ImageManipulation.LoadImage(model.Picture.InputStream);
                        if(picture==null)
                        {
                            return Content("FAIL:Niste poslali sliku");
                        }
                        picture = ImageManipulation.ResizeImage(picture, 160, 160);
                    }
                    var group = dbProvider.GetGroupsForUser(SessionData.User).FirstOrDefault(x=>x.Id==model.Id);
                    if (group == null || !(bool)group.IsAdmin) return HttpNotFound();
                    var oldMembers = dbProvider.GetUsersInGroup(group);
                    var newMembers = model.GetMembers();
                    var friends = dbProvider.GetFriends(SessionData.User).Union(dbProvider.GetUsersInGroup(group));
                    foreach (var user in newMembers)
                    {
                        if (user.Id == SessionData.User.Id || friends.All(x => x.Id != user.Id))
                        {
                            return HttpNotFound();
                        }
                    }
                    newMembers.Add(SessionData.User);
                    List<User> deletedMembers = new List<User>();
                    List<User> addedMembers = new List<User>();
                    foreach(var member in oldMembers)
                    {
                        if (!newMembers.Any(x => x.Id == member.Id)) deletedMembers.Add(member);
                    }
                    foreach (var member in newMembers)
                    {
                        if (!oldMembers.Any(x => x.Id == member.Id)) addedMembers.Add(member);
                    }
                    dbProvider.RemoveUsersFromGroup(deletedMembers, group);
                    dbProvider.AddUsersToGroup(addedMembers, group, false);
                    if(model.Name!=group.Name || model.Picture!=null)
                    {
                        if (model.Name != group.Name) group.Name = model.Name;
                        if (picture != null) group.Picture = ImageManipulation.StoreImage(picture);
                        dbProvider.UpdateGroup(group, picture != null);
                    }
                    dbProvider.CommitIfNecessary();
                    foreach(var member in deletedMembers)
                    {
                        MessengerHub.CallRefresh(member.RtID);
                    }
                    foreach(var member in addedMembers)
                    {
                        MessengerHub.CallRefresh(friends.First(x => x.Id == member.Id).RtID);
                    }

PSI Projekat/BrzeBoljeJeftinije.Messenger.UI/Views/Group/Edit.cshtml
@model BrzeBoljeJeftinije.Messenger.UI.Models.GroupModel
@{
    string successMessage = Model.Id == null ? "Grupa uspešno kreirana" : "Grupa uspešno ažurirana";
}
@using (Ajax.BeginForm("Edit", "Group", new { }, new AjaxOptions
{
    AllowCache = false,
    HttpMethod = "POST",
    OnBegin = "groupEditBegin",
    OnFailure = "groupEditFail",
    OnSuccess = "groupEditSuccess",

}, new { id = "group-edit-form", enctype = "multipart/form-data" }))
{
    <input type="text" class="form-control" id="group-edit-name" name="Name" placeholder="Unesite ime grupe" value="@Model.Name" />
    <input type="file" id="group-edit-upload-picture" name="Picture" style="display:none" accept="image/*" />
    <i class="fa fa-file-picture-o" style="padding-left:10px" aria-hidden="true" onclick="$('#group-edit-upload-picture').click()"></i><br />
    <input type="text" class="form-control" id="group-edit-search" placeholder="Unesite ime prijatelja" onkeyup="refreshGroupEdit()" />
    <ul id="group-edit-list"></ul>
    <input type="submit" class="form-control" onclick="submitGroupEdit()" value="@(Model.Id==null?"Kreiraj":"Sačuvaj")" />
    <input type="hidden" name="Members" , value="[]" id="group-edit-members" />
    <input type="hidden" name="Id" value="@Model.Id" />
}

<script>
    var groupEditMembers = [];
    var activeMembers = {}
    var oldEditMembers = @Html.Raw(Model.Members);
    function refreshGroupEdit()
    {
        $("#group-edit-list").html("");
        var searchQuery = $("#group-edit-search").val().toUpperCase();
        var handledMembers = {}
        groups.forEach((friend) =>
        {
            if (searchQuery.trim() == "") return;
            if (!friends[friend.otherId] || friend.name.toUpperCase().indexOf(searchQuery) == -1) return;
            if (activeMembers[friend.otherId]) return;
            handledMembers[friend.otherId] = true;
            $("#group-edit-list").append(renderChip("groupMemberClick(" + friend.otherId + ")", null, friend.picture, "fa-plus", friend.name, false));
        });
        groupEditMembers.forEach((friend) =>
        {
            if (searchQuery.trim() == "") return;
            if (friend.name.toUpperCase().indexOf(searchQuery) == -1) return;
            if (activeMembers[friend.id]) return;
            if (handledMembers[friend.id]) return;
            $("#group-edit-list").append(renderChip("groupMemberClick(" + friend.id + ")", null, friend.picture, "fa-plus", friend.name, false));
        });
        for (var friendId in activeMembers)
        {
            friend = activeMembers[friendId];
            $("#group-edit-list").append(renderChip("groupMemberClick(" + friendId + ")", null, friend.picture, "fa-minus", friend.name, false));
        }
    }
    function groupMemberClick(id)
    {
        if (activeMembers[id])
        {
            delete activeMembers[id];
            refreshGroupEdit();
        }
        else
        {
            var friendObject = null;
            groups.forEach((friend) =>
            {
                if (friend.otherId != id) return;
                friendObject = friend;
            });
            if (friendObject == null)
            {
                groupEditMembers.forEach((friend) =>
                {
                    if (friend.Id != id) return;
                    friendObject = friend;
                });
            }
            activeMembers[id] = friendObject;
            refreshGroupEdit();
        }
    }
    function groupEditBegin(event)
    {
        return false;
    }
    async function submitGroupEdit()
    {
        var members = [];
        for (var member in activeMembers)
        {
            members.push({ Id: member });
        }
        $("#group-edit-members").val(JSON.stringify(members));
        var formData = new FormData($("#group-edit-form")[0]);
        var response = await asyncAjax("/Group/Edit", formData);
        if (response.indexOf("FAIL:") != -1)
        {
            showAlertBox(response.replace("FAIL:", ""));
        }
        else
        {
            refreshGroups(false);
            showMessageBox("@successMessage");
        }
    }
    $(document).ready(() =>
    {
        for (var index in oldEditMembers)
        {
            var member = oldEditMembers[index];
            if (member.id == currentUserId) continue;
            groupEditMembers.push(member);
            activeMembers[member.id] = member;
        }
        refreshGroupEdit();
    });
</script>